### ISSUE TITLE
If term in navigation bar is not a website, search Google

### ISSUE THREAD

**Issue by sanek-stripe** [fonol/add-browser#3]
Basically, similar to how Firefox/Chrome/other browsers now work. When I type in "food", it shouldn't take me to `http://food/` but instead to a Google search for "food".

**Comment by fonol** [comment]
Hi, sorry for the late reply, I am short on time atm, but I will tackle that one when I got some time, as it is a rather easy change.

**Comment by sanek-stripe** [comment]
No expectations from my side! Just wanted to post it here as a feature request for future tracking -- might take a stab myself if I get some time

**Comment by fonol** [comment]
Done with newest update
